"use client"
import { Inter } from 'next/font/google'
import { signIn, signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Simulasi FRS',
//   description: 'Generated by create next app',
// }

export default function LayoutAdmin() {
  const {data:session, status} = useSession();
  const router = useRouter();
  // console.log(session);
  // console.log(status);
  useEffect(()=>{
    if(status === "unauthenticated" ){
      router.push('/')
    }
    else if(status==="authenticated" && session?.user?.role == "admin"){
      console.log(session,status);
    }
    else if(status==="authenticated" && session?.user?.role != "admin"){
      signOut()
      router.push("/")
    }
  }, [status])
  return (
          <div className='w-screen text-left space-x-5 p-5 bg-teal-600'>
            <a href='/homeAdmin' className='btn bg-teal-600 border-none float-left text-xl hover:text-black hover:bg-teal-600 text-white rounded-md px-3 '><h1>SIMULASI FRS</h1></a>
            <a href='/homeAdmin' className='btn bg-teal-600 border-none float-left  hover:text-black hover:bg-teal-600 text-white rounded-md px-3 '><h1>Jadwal Kuliah</h1></a>
            <a href='/jadwalUjian' className='btn bg-teal-600 border-none float-left  hover:text-black hover:bg-teal-600 text-white rounded-md px-3 '><h1>Jadwal Ujian</h1></a>
            {status === "authenticated" ? (
              <a href='/' onClick={()=>signOut()} className='btn bg-teal-600 border-none float-right hover:bg-teal-700 text-white rounded-md px-3 py-2'>Sign Out</a>

            ) : (
              <a href='/' onClick={()=>signIn()} className='btn bg-teal-600 border-none float-right hover:bg-teal-700 text-white rounded-md px-3 py-2'>Sign Out</a>
            )}
            <p className='float-right text-white px-3 py-2'>Hello, {session?.user?.name}</p>
          </div>
  )
}
