"use client"
import { Inter } from 'next/font/google'
import { signIn, signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
import LogoIF from '@/assets/logoIF.jpg'
import LogoUnpar from '@/assets/logoUnpar.png'
import logodouble from '@/assets/logoifunpar3.png'
import { PathParamsContext } from 'next/dist/shared/lib/hooks-client-context.shared-runtime';
import { images } from '@/next.config';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Simulasi FRS',
//   description: 'Generated by create next app',
// }

export default function LayoutUser() {
  const {data:session, status} = useSession();
  const router = useRouter();
  // console.log(session);
  // console.log(status);
  useEffect(()=>{
    if(status === "unauthenticated"){
      router.push('/')
    }
    else if(status==="authenticated" && session?.user?.role == "mahasiswa"){
      // console.log(session,status);
      // router.push(`/home/${session?.user?.role}/${session?.user?.email}`)
    }
    else if(status==="authenticated" && session?.user?.role == "admin"){
      router.push("/homeAdmin")
    }
    else if(status==="authenticated" && session?.user?.role != "mahasiswa"){
      signOut()
      router.push("/")
    }
  }, [status])
  return (
          <div className=' w-screen text-left lg:space-x-5 p-5 bg-sky-600'>
            <img src={logodouble.src} className='float-left w-24 h-13 rounded-xl scale-150 m-5'></img>
            <a href={`/home/${session?.user?.role}/${session?.user?.email}`} className='mt-1.5 btn bg-sky-600 border-none float-left text-xl hover:bg-sky-700 text-white rounded-md px-3 '><h1>SIMULASI FRS</h1></a>
            <a href={`/home/${session?.user?.role}/${session?.user?.email}`} className='mt-1.5 btn bg-sky-600 border-none hover:bg-sky-700 text-white rounded-md px-3 py-2'>Home</a>
            <a href={`/simulasi/${session?.user?.role}/${session?.user?.email}/${session?.user?.id}`} className='btn bg-sky-600 border-none hover:bg-sky-700 text-white rounded-md px-3 py-2'>Simulasi FRS</a>
            {/* <a href={`/daftarMataKuliah/${session?.user?.role}/${session?.user?.email}/${session?.user?.id}`} className='mt-1.5 btn bg-sky-600 border-none hover:bg-sky-700 text-white rounded-md px-3 py-2'>Daftar Mata Kuliah</a> */}
            {status === "authenticated" ? (
              <a href='/' onClick={()=>signOut()} className='mt-1.5 btn bg-sky-600 border-none lg:float-right float-left hover:bg-sky-700 text-white rounded-md px-3 py-2'>Sign Out</a>

            ) : (
              <a href='/' onClick={()=>signIn()} className='mt-1.5 btn bg-sky-600 border-none lg:float-right float-left hover:bg-sky-700 text-white rounded-md px-3 py-2'>Sign Out</a>
            )}
            {/* <a href='/' className='btn bg-sky-600 border-none float-right hover:bg-sky-700 text-white rounded-md px-3 py-2'>Sign Out</a> */}
            <img className="float-right w-10 h-10 mt-3.5 rounded-full" src={session?.user?.image}></img>
            <p className=' text-xs lg:text-base mt-4 lg:mt-2 float-right text-white px-3 py-2'>{session?.user?.name}</p>
          </div>
  )
}
